spring:
  kafka:
    bootstrap-servers: 192.168.118.81:9092,192.168.119.103:9092,192.168.118.213:9092
    consumer:
      auto-offset-reset: earliest
      group-id: test-consumer-group
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer           
      bootstrap-servers: 192.168.118.81:9092,192.168.119.103:9092,192.168.118.213:9092
    listener:
      concurrency: 3
    producer:
      batch-size: 1000
    template:
      default-topic: kafkatest
kafka.zookeeper.connection: 192.168.118.81:2181,192.168.119.103:2181,192.168.118.213:2181
kafka.zookeeper.session_timeout: 30000
kafka.zookeeper.connect_timeout: 30000
